### ISSUE TITLE
小薇任务3

### ISSUE THREAD

**Issue by levinit** [miaogushine/Baidu_ife_task#1]
路过
你这样写有问题的，你拉缩浏览器试试，右边的会间距拉大或消失。
不要用overflow hidden

左右浮动 中间margin  中间不要定宽度
子元素浮动父元素可能塌陷用清除浮动解决。
http://www.jianshu.com/p/f09f40591d97
http://www.iyunlu.com/view/css-xhtml/55.html

共勉

**Comment by miaogushine** [comment]
好的，非常感谢
